# configs/continual_montgomery.yaml
data:
  shen_csv_path: "C:/Users/offic/OneDrive/Masaüstü/datasets/SelfSupervised/Shenzhen/shenzhen_metadata.csv"
  shen_img_dir:  "C:/Users/offic/OneDrive/Masaüstü/datasets/SelfSupervised/Shenzhen/images/images"
  mont_csv_path:"C:/Users/offic/OneDrive/Masaüstü/datasets/SelfSupervised/Montgomery/montgomery_metadata.csv"
  mont_img_dir: "C:/Users/offic/OneDrive/Masaüstü/datasets/SelfSupervised/Montgomery/images/images"

dataloader:
  batch_size: 32
  num_workers: 0
  shuffle: true
  pin_memory: false
  seed: 42

model:
  ssl_ckpt_path: "C:/Users/offic/medself/shenzhen_ckpts/epoch=11-aucval_auc=0.896.ckpt"
  mem_size: 200
  ewc_lambda: 0.05

training:
  shen_epochs: 5
  mont_epochs: 15
  lr_shen: 1e-4
  lr_mont: 3e-4

trainer:
  accelerator: "gpu"
  devices: 1
  log_every_n_steps: 20
  gradient_clip_val: 1.0
